{{- if semverCompare ">=1.21" .Capabilities.KubeVersion.Version -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "backup-k8s-postgres.fullname" . }}
  labels:
    {{- include "backup-k8s-postgres.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.config.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "backup-k8s-postgres.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "backup-k8s-postgres.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: AZURE_BLOB_CONTAINER
                  value: {{ .Values.config.storageContainer }}
                - name: BACKUP_PREFIX
                  value: {{ .Values.config.prefix }}
                - name: AZURE_STORAGE_ACCOUNT_NAME
                  value: {{ .Values.config.storageAccount }}
                - name: AZURE_STORAGE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.config.storageAccountKeySecret }}
                      key: {{ .Values.config.storageAccountKeySecretKey }}
                - name: PGHOST
                  value: {{ .Values.config.postgresHost }}
                - name: PGPORT
                  value: "{{ .Values.config.postgresPort }}"
                - name: PGDATABASE
                  value: {{ .Values.config.postgresDatabase }}
                - name: PGUSER
                  value: {{ .Values.config.postgresUser }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.config.postgresPasswordSecret }}
                      key: {{ .Values.config.postgresPasswordSecretKey }}
                - name: PUSHGW_ENABLED
                  value: {{ .Values.config.pushgwEnabled | quote }}
          serviceAccountName: {{ include "backup-k8s-postgres.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
