apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backup-pvc.fullname" . }}
  labels:
    {{- include "backup-pvc.labels" . | nindent 4 }}
spec:
  schedule: {{ required "schedule must be specified" .Values.schedule }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backup-pvc.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "backup-pvc.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ required "azureSecretName must be specified" .Values.azureSecretName }}
                  key: {{ .Values.azureSecretAccountKey }}
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.azureSecretName }}
                  key: {{ .Values.azureSecretKeyKey }}
            - name: BACKUP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.encryptionsSecretName | default .Values.azureSecretName }}
                  key: {{ .Values.encryptionSecretKey }}
            volumeMounts:
            - name: personio-sync-persistence
              mountPath: /backup-src
          restartPolicy: OnFailure
          volumes:
          - name: personio-sync-persistence
            persistentVolumeClaim:
              claimName: {{ required "PVC name must be specified." .Values.backupSourcePVC }}
